### ISSUE TITLE
Example objects do not build in the Max 7 SDK

### ISSUE THREAD

**Issue by opendragon** [Cycling74/max-sdk#10]
There is a bug in the 'build.rb' script that is used to build the example objects in the Max 7 SDK.

Details:
Steps to reproduce:
1) install the SDK In the recommended location ($HOME/Documents/Max 7/Packages/).
2) cd $HOME/Documents/Max 7/Packages/max-sdk/source
3) type 'ruby build.rb' and watch all the build failures...

To fix - the line 'result = `cd...`' needs to be fixed to allow spaces in the directory path.
[build.rb.patch.txt](https://github.com/Cycling74/max-sdk/files/36948/build.rb.patch.txt)

**Comment by tap** [comment]
Fixed.  Thanks!
