### ISSUE TITLE
search text field in html offline documentation is broken

### ISSUE THREAD

**Issue by theod** [Cycling74/max-sdk#13]
no result are returned when trying to use the top right text field

**Comment by theod** [comment]
I use safari to display it in case it is related... but @jkcmusork suspects missing doxygen export options

**Comment by tap** [comment]
Hi @theod -- This is just the way Doxygen works.  That search field only works for symbols in the API, not for any text.  So if you search for `t_atom` it will work, but search for `atoms` and it probably won't.
