### ISSUE TITLE
Floating point formats generate random strings

### ISSUE THREAD

**Issue by opendragon** [Cycling74/max-sdk#14]
Using any floating-point format (%e, %E, %f, %F, %g, or %G) in one of the Max-supplied output routines (snprintf_zero, post, cpost, et cetera) generates random output, usually zero.
Using sprintf or snprintf, from the C/C++ library, does work.
E.g.

    double number = 42.34;
    char  buffer[SUGGESTED_BUFFER_SIZE_];

    snprintf(buffer, sizeof(buffer), "%g", number);

works, while

    snprintf_zero(buffer, sizeof(buffer), "%g", number);

doesn't.

**Comment by tap** [comment]
I've personally not experienced this (I typically use `%f`).  Can you please provide details about platform, architecture, etc.  

Also potentially useful are any project/target settings that might impact memory alignment, struct packing, etc.

**Comment by opendragon** [comment]
Hi Timothy: 

I'm at work right now; when I get home - in about 8 hours - I'll look through my project settings, and compare them with the 'dummy' project; I used the 'maxmspdsk.xconfig' settings and the 'dummy' project as the basis for my builds. 

I'm running on Mac OS X 10.11.1 / El Capitan, and build for 64-bit/32-bit; the same problem occurs when I simply build for 64-bit. 
I don't use struct packing, and the problem occurs when any double variable - on the stack, heap or global - is passed to one of the formatted output routines. 
----- Original Message -----

**Comment by opendragon** [comment]
Hi Timothy: 


I duplicated the 'dummy' project, added some calls using floating-point format, built the external, copied it to a Max externals folder, loaded it in Max 7 and it worked. 
I then duplicated one of my projects, renamed it to 'dummy2', replaced the source code with the 'dummy' project source file, built the external, copied it to the same Max externals folder, loaded it in Max 7 and all sorts of weirdness ensued. 
Yesterday I compared the build settings between one of my projects and the working 'dummy' project, and they are identical, except for filename references. 
I clearly have missed something and will look at the settings very carefully... it might even be a link order issue. 
I won't be able to do this until this evening, but I'll let you know if I find the 'smoking gun'. 
If I can't, I can package the offending project into a ZIP file and send it to you. 
----- Original Message -----

**Comment by jeremybernstein** [comment]
Yes, please up the project and send it along.

**Comment by opendragon** [comment]
Hi Jeremy: 


I found the problem - my version of maxmspsdk.xconfig had a setting for 'OTHER_LDFLAGS' that was bringing in some APIs and including 'C74_SYM_LINKER_FLAGS' and I was explicitly linking with the MaxAPI framework. The other project did not have a setting for 'OTHER_LDFLAGS' but explicitly set it to 'C74_SYM_LINKER_FLAGS' in the project itself and did not link with the MaxAPI framework. 
I believe that I did it this way due to the old way that I built my objects. 
Once I uncommented the setting for 'OTHER_LDFLAGS' and removed the explicit linking with the MaxAPI framework, my copy of the 'dummy' project behaved like the other project. 
I then tested one of my standard objects, that had been modified to include calls to 'post' for testing, to confirm that this was the cause. 
Since the project settings had appeared to be identical - I had missed the explicit inclusion of 'C74_SYM_LINKER_FLAGS' as opposed to the implicit inclusion via maxmspsdk.xconfig, and had not compared the link phases of the builds - I had missed the difference(s) that caused the problem. 
I believe that the issue can be closed, and I can proceed with fixing my projects to build correctly! 
----- Original Message -----

**Comment by tap** [comment]
Thanks for explaining @opendragon -- I can confirm that you do *not* want to link against MaxAPI.framework.  That is a relic that has been left in the SDK as a "convenience" so that people don't have to update old projects.  As you found, however, it may just be causing confusion.
