### ISSUE TITLE
error in simplejit example ? 

### ISSUE THREAD

**Issue by p1nh0** [Cycling74/max-sdk#18]
Only char type seems to be working properly.

I am sending a matrix from jit.noise to jit.simple (with autoadapt=1) and when I change the jit.noise matrix type to other than char I get incorrect values after jit.simple. Here's what is happening: 
char: correct values
long: wrong values
float32: always gives "0."
float64: always gives "0."

**Comment by tap** [comment]
Does the jit.simple help patcher work correct?

**Comment by p1nh0** [comment]
Yes the help patcher works fine. The problem seems to be when I "inject" a matrix from jit.noise into jit.simple.
I'm also on Max7.1 64bits, OSX 10.10 and Xcode 7.1.1

**Comment by tap** [comment]
Thanks for clarifying @p1nh0 -- could you please attach/paste a patcher into this thread to demonstrate?  Thanks.

**Comment by p1nh0** [comment]
<pre><code>
----------begin_max5_patcher----------
1484.3oc0ZssiihCD84juBDOmsE1bM6SY+NZ0JxDbHtGhMBLcmdGM+6qu.Dt
l.YRxzajZPT9VcNtb4pr6etbgYH6DN2z3uMd0XwhetbwBkHofEkeuv7H5ztD
TtpZl6XGOhobyU5x33Sbkbd1WF6NfnwDZrA+qTbUMRHT7NVAUUMXovvhvvDr
TBnTBs3Hqfmf4pgwpTZN+Kc0Lq5tTDe2AwXrMCuiqUban+KVqL.vWbEOsfxO
rEhLd6beSnUcc0.RhT8KK78+JvTJ5WKWJerZhDQXAmynlCp9fQUeckT7iR2M
CETlYslN.5b.R7.sTOcpdNYrA.2B3n3OEMt2j76D9KTFIGarQBAi8ILD2FZr
IhbzvE.MbfNFaRSPkS4FNCyOvoyOhgb6QDOibxbknZWmoBbUbzZ8K3bnpago
NhyyQw3dTUIa7aaebYDuVYPXaod44ofrcCHumQ44j+UuRSTvPLArOSXa1n8T
zQsN9OYDTx8jiD9KxdvDDz8gPPtOGB5Aa9XqWwTxN9N2K1w+9xNi3LJS.VrQ
CmMJWRBOQCSZNyfzV03uIPfPea0KW3MwfN8YPn2SgBk9y0NWIz8rmhwFrzKs
0MQUC30115oPUoF4ojjDye+vUbpvthHbbtWDwkLYZpM3rRzWBeQCHI3OvY4D
Q7Lm66ElnzzFhWznIRN6clpi7WUKhP0h.0hxvePpZuUsTTlfS3BBoHSqjm7p
7zI6FVDNiVPT8jVnX1aYUGd1dR4zZsxwtihRULaEMJlmiSX69ANp4faxRwTB
MMCmKhhEw6nalQ38nhD91VyAvWFr78nc3Qa7fS.KLiyHQLpTIZwzRwUC2qF.
0lVxmmAipFTT5.MVL4KXkQJLW.xh7PTlbhnLlaXUgbFKocQ0sKAumWVbJgR6
vhbV53ElQhObg1FxDEd7R8spj7sETcoaEqM4ayQezls4njjxEqs69SHJQ3UC
yI5o.nUcgXJR.zC46xXh0xMwqtjOFnjHgM7N7mjH9A0.0zXPTcRZkQjY8rbD
IFmyaKiihyaKom2Bgnhvx0na43ih813cpPq70ZtfroasVx63diyhiSv0q1TN
ExD1pbwPp4fVqUGa6fQ.vfaKPj498VqQr+tCAJSdvvY4Lp+u9QdTIV40uz2w
MRUs1In8tAwxIl6IGMQBxQkoq10WybaFMrrdAVbOIn1gs1lgxw7mKA4Jy9Wm
7ms5j.5wOi3SepTmmYm9ZfXMdbD6im.gkKAUFWtqUwxB7u.GFLaJz94QgWXw
qLpWUvbFaRH4BZhFyOX.A9VAAiS4vafxWM4E1ZCWfGnazfWHhvI6UD77nckt
bWsaab.PWiJWqXO8A+T+bbWjVCyVtMUmpi6TolCvSmCPSdNmiryrRUkkOLAl
yJx1UA2x7mMZq2hHM3DZc3puV4Lua8NPhhvztfKhjK2XWGl0jlrmqF6MQM19
aiF6NCNF7sPigSTiAea3XvLrJlBGejDkxDQSVtLSDLj7.+AVxWd5WpuZOjWA
lFusrYJllx7Lh1pyoZKhKb7DVv0qraly7rh8WjHZHJoLx9ZmuWJQfyYKr7r9
d+NzmbhH4BrwFTDJkK39MwHB0.7xy+35A5CpG36euNGD3c9vYk7U5mDZD6yp
NNDs6GwYrBZz3WgE7hmt3DtwmxWhPBrE+bbjbk2LtNCny+KPqq+KAB7ACj2f
m5XbBVqPrsmXUs6b.7sfW4J7BRETkeoSStwMX9XNOz.6l2qm07uspVvU0r1w
fnQeWe1kbvk8UOk3M56ituq1dyE2Usw84oNSQe.OO0A9sRcjm.+0ms7dZ5Sm
gZX8wuYLGCnNch0v1UEdAbs9XXrbq+573beA.3J.vcd.vQjdOvS7y+LJB.Ob
T.uBJrmGJbEDefZyA40VpS2SOyn95QfB2IXLcMa6dnPe9T15Yg00e8mR+6rB
dx.PYFY23q+T.P9OZwM4cQuuYmK5RpJctfqNWtU+K1Z7K0p6EZIF4es7+.jl
tzXJ
-----------end_max5_patcher-----------
</code></pre>

**Comment by tap** [comment]
Thanks!  Should be fixed now.
