### ISSUE TITLE
Please update latest release

### ISSUE THREAD

**Issue by adamflorin** [Cycling74/max-sdk#23]
It looks like a few changes have gone into `master` since the last release (v7.1.0)—most importantly, 84044d393f62d80e8ef32b9adb6fbcb2d89a6149, which fixes building externals on macOS Sierra. Could you please make a new release here on GH and in the AWS download from cycling74.com? Not having the latest code caused me some confusion. Thanks!

**Comment by tap** [comment]
I've updated the latest release on Github to v7.3.3. Hope this helps!

**Comment by adamflorin** [comment]
Thanks @tap! If you're able, it would extra helpful to update the version at https://cycling74.com/downloads/sdk too, for those who don't know about the GH repo… 🙌

**Comment by tap** [comment]
Yes @adamflorin , the site is being updated too -- that just takes a day or two before the updates make it through the pipeline.

**Comment by adamflorin** [comment]
Ah, got it, sorry to nag. Thank you!
