### ISSUE TITLE
opinion on const for common (t_object *x, ...) or (void *x, ...) or (... t_class *c ...)

### ISSUE THREAD

**Issue by diablodale** [Cycling74/max-sdk#26]
Throughout the SDK, a pointer to an instantiated class, object, or a class itself is needed. The SDK is built with the concept of having a pointer to an object and then manipulating the deferenced object. Any change involving this core concept is pervasive. Hence, my inquiry.

I suggest that in the majority of the cases, pointers to these three "objects" can be const or const-to-const to increase type-safety. In addition, use of const provides hints to the compiler which may improve speed and/or size.

Opinions, cautions?

The reasoning is that code shouldn't alter the pointer to the object on which the code is manipulating. Code can dereference the pointer and operate on the object itself...but not alter the pointer to the object. Altering the pointer to the object risks loosing access to the object, memory/security exceptions, and other negative situations. For the very few cases in which a coder needs to manipulate the pointer itself, they can copy/cast it into a mutable form.

### Examples of API calls (original and const'd)

```cpp
t_max_err class_register(t_symbol *name_space, t_class *c);
t_max_err class_register(const t_symbol * const name_space, t_class * const c);

t_max_err object_method_typed(void *x, t_symbol *s, long ac, t_atom *av, t_atom *rv);
t_max_err object_method_typed(void * const x, const t_symbol * const s, const long ac, const t_atom * const av, t_atom * const rv);

t_max_err object_attach_byptr(void *x, void *registeredobject);
t_max_err object_attach_byptr(void * const x, void * const registeredobject);

t_max_err object_notify(void *x, t_symbol *s, void *data);
t_max_err object_notify(void * const x, const t_symbol * const s, void * const data);

attr_args_process(void *x, short ac, t_atom *av);
attr_args_process(void * const x, const short ac, const t_atom * const av);

t_max_err object_attr_setfloat_array(void *x, t_symbol *s, long count, float *vals);
t_max_err object_attr_setfloat_array(void * const x, const t_symbol * const s, const long count, const float * const vals);

t_max_err class_addattr(t_class *c,t_object *attr);
t_max_err class_addattr(t_class * const c, t_object * const attr);
```

### Examples of callbacks

(method) a core typdef defined in the headers as `typedef void *(*method)(void *, ...);` is one source of these non-const pointers with callbacks.

```cpp

max_jit_class_addmethod_usurp_low(max_class, (method)max_myfunc, "doit");
void max_myfunc(t_max_my_obj *x, t_symbol *s, long argc, t_atom *argv)
 ↓ ↓ ↓ ↓ ↓
typedef void *(*method)(void * const, ...);
max_jit_class_addmethod_usurp_low(max_class, (method)max_myfunc, "doit");
void max_myfunc(t_max_my_obj * const x, const t_symbol * const s, const long argc, const t_atom * const argv)

or

t_max_err max_my_custom_setter(t_max_my_obj * const x, t_object * const attr, const long argc, const t_atom * const argv)

```

However, when `(method)` is used for some callbacks, it doesn't have a strong const intention. For example, the `fun()` callback for `schedule()` passes any `void *ob` as the first param to fun(). This param doesn't have to be one of the three "objects" above; though it probably is. There may be a slightly larger set of scenarios here than in the message/attribute callbacks above; though, I believe it is still rare.

```cpp
void schedule(void *ob, method fun, long when, t_symbol *sym, short argc, t_atom *argv);
              ↑↑↑↑↑↑↑↑↑
              In a radical scenario, fun() wants to alter its copy of pointer.
```

### Notes

For greatest overall improvements, the static/dynamic libraries for Max would need to be re-compiled with the const changes. I consider this outside the scope of this issue report, yet worth mentioning.

**Comment by tap** [comment]
These are good points. Some items are more actionable than others.

First, I'd like to make mention of the Max-API project at https://github.com/Cycling74/max-api

In this (the Max-SDK project) we have to be incredibly sensitive to a myriad of cases where backward compatibility (in several different forms) issues can arise. With this legacy it is difficult to make changes like you have proposed.

The Max-API project, however, was created specifically for the purpose of improving type safety, increasing our use of modern best practices, and making the Max headers work better in a C++ ecosystem (e.g. using namespaces).

So... while these observations are very valid in the Max-SDK, addressing them is something more applicable to the Max-API.

I hope this is not too confusing!

**Comment by diablodale** [comment]
Got it. You gave me enough on which I can work. Thanks.
I'll consider this issue closed for the max-sdk as an intentional "won't fix" due to legacy concerns.
