### ISSUE TITLE
call graph link fails, likely due to missing toggleVisibility()

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/max-sdk#3]
Repro:

    Use Chrome (or offline docs)
    Visit https://cycling74.com/sdk/MaxSDK-7.0.3/html/group__class.html#ga2fa22e46d14006d0de5cde70af1f6221
    In the section for ext_main() click on the "Here is the call graph for this function"

Result
Nothing happens. No graph is shown.

Continued repro
3. Press ctrl+shift+I

Result:
Two errors are shown

Uncaught ReferenceError: NAVTREE is not definedinitNavTree @ navtree.js:472(anonymous function) @ group__class.html:68b.Callbacks.e @ jquery.js:16b.Callbacks.bD.fireWith @ jquery.js:16bF.extend.ready @ jquery.js:16e @ jquery.js:16

Uncaught ReferenceError: toggleVisibility is not definedonclick @ group__class.html:872

**Comment by tap** [comment]
This has been fixed internally for the upcoming Max 7.1 SDK.
