### ISSUE TITLE
Is this repository accepts any pull request from any user ?

### ISSUE THREAD

**Issue by leico** [Cycling74/max-sdk#30]
Hi C74 Dev team.

About subject matter, if yes, I would like to try additional comments in
https://github.com/Cycling74/max-sdk/blob/86a11ba0ed4b66152362d4b807e3f5a1b989d3fe/source/c74support/msp-includes/ext_buffer.h#L214

**Comment by tap** [comment]
Hi @leico,

Yes, we accept pull requests from any user. Before we review the pull request we ask that you sign our CLA here: https://docs.google.com/forms/d/e/1FAIpQLSeln1ccy7hnrs-1GNxfCZS8lwh1oUY8bYCPZUwCTjB7gbPB2g/viewform

Thanks!
  Tim
