### ISSUE TITLE
outlet_list(): subtle documentation mistake?

### ISSUE THREAD

**Issue by andreaagostini** [Cycling74/max-sdk#35]
Hi,

the documentation for outlet_list() states that the second argument can be either NULL or gensym("list"), but if I set it to NULL and subsequently watch the message in the Max debugger I see <unknown> in the "Message" column. Apart from this, the message appears to be correct. 

I suggest to change the documentation, stating that the second argument must be the "list" symbol.

Cheers,
andrea

**Comment by tap** [comment]
Thanks @andreaagostini !
