### ISSUE TITLE
search box in top right fails

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/max-sdk#4]
Repro:

    Use Chrome
    Visit https://cycling74.com/sdk/MaxSDK-7.0.3/html/index.html
    In the top right search box type:  standalone

Result
Nothing happens.

Expected:
Search results matching the text "standlone"

Continued repro
3. Press ctrl+shift+I

Result:
Two errors are shown

Uncaught ReferenceError: NAVTREE is not definedinitNavTree @ navtree.js:472(anonymous function) @ index.html:68b.Callbacks.e @ jquery.js:16b.Callbacks.bD.fireWith @ jquery.js:16bF.extend.ready @ jquery.js:16e @ jquery.js:16

2search.js:323 Uncaught ReferenceError: indexSectionsWithContent is not definedSearchBox.Search @ search.js:323(anonymous function) @ VM570:1

**Comment by tap** [comment]
This is a limitation of Doxygen.  Relevant bit is here: https://www.stack.nl/~dimitri/doxygen/manual/searching.html

The relevant bit:

    it is limited to searching for symbols only. It does not provide full text search capabilities, and it does not scale well to very large projects
