### ISSUE TITLE
proxy_delete documentation?

### ISSUE THREAD

**Issue by FrancescElies** [Cycling74/max-sdk#49]
Hi,

The only documentation I see for `proxy_delete`
```c
void proxy_delete(void *xx); // calls inlet_delete()
```

After some trial and error I discovered you should not call  `object_free` after proxy_delete.

I cannot find this function in max_api generaded docs. Is it safe for me to use this function in combinations with `proxy_new` & `proxy_getinlet`?

**Comment by jeremybernstein** [comment]
You should call `freeobject` or `object_free` on your proxy when you're done with it. You don't need to call `proxy_delete()`

**Comment by FrancescElies** [comment]
@jeremybernstein thanks for the quick reply.

After adding a new proxy with `proxy_new` if I want to delete it it felt natural to call `proxy_delete`. Any special reason why I shouldn't do that? If so, could we document it? (happy to make a pr if desired).

Background: I have an external with dynamic inlet/outlet

**Comment by FrancescElies** [comment]
Ok thanks for the clarification, maybe we could add a comment on the header file, what do you think?

Since my original question has been clarified, please feel free to close this issue.

**Comment by FrancescElies** [comment]
I am a bit confused, 

If I do the following;
```c
x->m_proxy = proxy_new((t_object *)x, 1, &x->m_in);
```
And later on I call the following function when I want get rid of an inlet
```c
object_free(x->m_proxy);
```

The object gets freed but the inlet does not disapear from the external

If I call `proxy_delete` instead the inlet goes away and I guess the memory get's freed too.
In this case apparently I can run into double free issues.
```c
proxy_delete(x->m_proxy);
```

As you and the max api docs also suggest, I should use `object_free`,
but then how do I tell the external that the freed proxies shouldn't be
available/rendered?

**Comment by jeremybernstein** [comment]
Are you trying to generate/delete inlets at runtime? That's not currently supported for 3rd party externals, and `proxy_delete()` is only intended for internal use. Which is to say, you're free to hack on this, but we can't offer much in the way of support or additional documentation than what's there.

**Comment by FrancescElies** [comment]
Yes exactly, generate/delete inlets ar runtime.

Ok that's fine, can you at least promise :) that this function will be available in future api versions, or could it be deleted at anytime?

**Comment by jeremybernstein** [comment]
As I said, it's for internal use. In general, we don't "un-export" stuff that we've made public in any fashion, so you can probably rely on it being available for the foreseeable future.
