### ISSUE TITLE
locatefile_extended() documentation need more numtypes param usage

### ISSUE THREAD

**Issue by diablodale** [Cycling74/max-sdk#5]
locatefile_extended() documentation in pdf/html needs additional info on the usage of numtypes=-1

When -1 is passed as the value of numtypes, the API will search for all filetypes and not limit it by the filetypelist param.

Typical usage is:
locatefile_extended(filename,&vol,&type,&type,-1)

**Comment by jeremybernstein** [comment]
Better is just to pass NULL, 0 as the final arguments. We had to fix some bugs related to the use of -1 earlier this year, in fact. So I would rather clean up any projects where this (old, ugly, unnecessary) format is used than update the documentation to document it.

**Comment by diablodale** [comment]
I learned this from the max sdk examples. I see three still exist: filebyte.c, filedate.c, filein.c

**Comment by tap** [comment]
This has been addressed in the upcoming Max 7.1 SDK updates.

**Comment by diablodale** [comment]
What are the changes (code and/or documentation text) that is to be updated? I request it here so that I can review it for understanding + for future people when they search for and find this issue.
