### ISSUE TITLE
path_toabsolutesystempath() doesn't return path on Windows ready for libraries

### ISSUE THREAD

**Issue by diablodale** [Cycling74/max-sdk#7]
The SDK 6.1.4 documentation writes that path_toabsolutesystempath()
>Translates a Max path+filename combo into a correct absolutepath that can be used to pass to libraries expecting system-native paths

Unfortunately, on Windows it does not. Instead it returns a path that uses forward slashes to separate directories. This reproduces on Max 6.1.9 and Max 7.0.6 both x86 and x64 using SDK 6.1.4.

To make a path that is ready "to pass to libraries" a backslash needs to be used to separate directories. This errant behavior does have a workaround. One can do the following:
```
path_toabsolutesystempath(pathid, "", filestring);
path_nameconform(filestring, sNativeQualifiedPathname, PATH_STYLE_NATIVE, PATH_TYPE_PATH);
```

**Comment by tap** [comment]
Thanks, Dale.  The documentation can be tweaked.  The "workaround" is in fact the correct code for you to be using.

**Comment by diablodale** [comment]
works for me.

**Comment by tap** [comment]
documentation has been updated in the upcoming Max 7.1 SDK updates.

**Comment by diablodale** [comment]
What is the documentation text that is to be updated? I request it here so that I can review it for understanding + for future people when they search for and find this issue.
