### ISSUE TITLE
atom_setfloat() lacks 32-bit floats, corrupts data on Max 32-bit, not consistent with other float atom APIs

### ISSUE THREAD

**Issue by diablodale** [Cycling74/max-sdk#8]
I request an API, macro, etc. that allows setting a 32-bit float into an atom.
While a dev can use atom_setfloat() by casting the float param up to a double, it is less performing plus results in erroneous results.

Accepting a double implies a 64-bit float. However, atoms on 32-bit Max are restricted to 32-bit values/floats. Therefore, corrupting the data if a dev sends a double into this API.

It can't make a roundtrip of atom_setfloat()  ->  atom_getfloat().  The values will not be the same.

The lack of a `t_max_err atom_setfloat(t_atom *a, float b)` doesn't match the pattern of the other atom APIs like:
atom_setfloat_array
atom_setdouble_array

Perhaps this API can be adjusted to be
`t_max_err atom_setfloat(t_atom *a, t_atom_float b)`

or creating two new APIs like
`t_max_err atom_setfloatEx(t_atom *a, float b)`
`t_max_err atom_setdouble(t_atom *a, double b)`

**Comment by tap** [comment]
This is unlikely to change, as this part of the API has been stable for well over a decade.  

I'm also not sure I follow what you mean about data becoming corrupted.  These functions pass by value and if a double needs to be down-cast to a float then it happens accordingly.

**Comment by diablodale** [comment]
I get that it is old code and you don't want to touch what worked 10 years ago. Yet the code has errant behavior. That's why I suggest new APIs which match today's world.
- Max is 64-bit now. I think it should recognize the existing and difference in float sizes in 32 and 64-bit builds and generate correct output.
- Compilers can and do use SSE2 now
- Developers want 32 and 64 bit float support at low perf cost.

The corruption scenario is what I wrote above: a roundtrip of atom_setfloat() -> atom_getfloat() will fail to be the same value for a gigantic set (at least 10^307) of floating point values.
```
t_max_err floaterr = MAX_ERR_NONE;
t_atom floatatom;
double floatin = DBL_MAX;
t_atom_float floatout;
DPOST(PLATFORM_STRING " floatin=%f", floatin);
floaterr = atom_setfloat(&floatatom, floatin);
DPOST(PLATFORM_STRING " atom_setfloat(floatin) err = %Id", floaterr);
floatout = atom_getfloat(&floatatom);
DPOST(PLATFORM_STRING " atom_getfloat() = %f", floatout);
```
On x86 compile results in:
```
Win32 floatin=1.797693e+308
Win32 atom_setfloat(floatin) err = 0        <---- no error was reported
Win32 atom_getfloat() = 1.#INF00e+000        <---- data has been corrupted
```
On x64 compile results in:
```
Win64 floatin=1.797693e+308
Win64 atom_setfloat(floatin) err = 0
Win64 atom_getfloat() = 1.797693e+308         <---- correct roundtrip
```

The param value of double on the API additionally causes a casting/conversation between double<->float. For example, on x86, I suspect something like the following occurs:
1. float values in customer code are cast up to a double to match the needed param type on the API. This costs various cycles depending on if the code was compiled with SSE2 support and what hardware is actually running the code
2. Inside the API the double passed in is cast down to a float to fit within the atom. This costs various cycles depending on if the API library was compiled with SSE2 support and what hardware is actually running the code.

Worst case is a twice paid multiple-cycle cost on x86 due to float->double->float. This isn't cheap. And I suspect these atom APIs are on critical code paths for developers.

Using doubles everywhere saves one set of conversions but then introduces the possibility for corruption due to the flaw demonstrated above.

**Comment by tap** [comment]
The round trip problem with 64->32->64 bits will of course result in data reduction and non-equal results.

The atom on 32-bit machines is 32-bits.  Changing the API for the atom will not change the fact that the atom itself is still only 32-bits.  The atom cannot be changed -- the code in many many places (including 3rd-party externs) would break if the size of the struct changed.

If you need to pass doubles between objects in 32-bit Max then I suggest you use MSP, Jitter, A_CANT methods, or something creative with dictionaries.

I'll close this issue as there is no problem with API, the problem you experience is simply with with 32/64 bit conversions.

**Comment by diablodale** [comment]
Then lets agree to disagree on this issue.

I would encourage developers reading this issue to be cautious with the atom_setfloat() API. It will corrupt floating point values for the vast majority of double param values passed to this API when compiled on x86. No warning, no error, no notice. There will also be a performance penalty on x86 for the float 32->64->32 that this API forces occur. There is no safe workaround for these issues at this time.
